permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Andrew Schuster
description: "I post stuff here"
# email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://schusteasy.com"
repository: "https://github.com/aschuster3/aschuster3.github.io"
#disqus_shortname: "fernandomoreira"

# social footer
social:
  github:
    slug: github
    link: http://github.com/aschuster3
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/andrew-schuster-36bb7664
